"""Bootstrap replicates with deterministic chunking, checkpointing and resume (prereg §6.2, contract §C4.5).

Replicate b is generated by `default_rng([20260907, phase, cell_index, b])` and, within a
replicate, the 1920 circuit records are resampled in ascending (n, seed index, scale index)
order. Because each replicate's stream is seeded by its own b and consumed in full inside that
replicate, the set of replicates {b_lo .. b_hi} computed in one chunk is bit-identical to the
same replicates computed one at a time or in any other chunking. The 2-D multinomial call is
bit-identical to the sequential per-record calls (evidence 1b-00, test in
tests/test_phase2_bootstrap.py). Chunks are written as .npz checkpoints keyed by their b-range;
`run` skips finished chunks, so a resume after an interruption continues exactly where the
stream stopped, and `assemble` concatenates the chunks in b order.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Callable

import numpy as np

from .contract import BOOT_SEED_BASE

ReplicateFn = Callable[[np.ndarray], dict[str, np.ndarray]]  # V[b, n, k, j, q] -> named arrays over b


def rng_for(phase: int, cell_index: int, b: int) -> np.random.Generator:
    return np.random.default_rng([BOOT_SEED_BASE, phase, cell_index, b])


def resample_chunk(counts: np.ndarray, shots: np.ndarray, phase: int, cell_index: int, b_lo: int, b_hi: int) -> np.ndarray:
    """counts[n, k, j, 2^L] int, shots[n, k, j] int -> V-like resampled counts [B, n, k, j, 2^L] for b in [b_lo, b_hi)."""
    N, K, J, D = counts.shape
    flat = counts.reshape(N * K * J, D)
    p_hat = flat / flat.sum(axis=1, keepdims=True)
    nvec = shots.reshape(N * K * J)
    out = np.empty((b_hi - b_lo, N * K * J, D), dtype=np.int64)
    for i, b in enumerate(range(b_lo, b_hi)):
        rng = rng_for(phase, cell_index, b)
        out[i] = rng.multinomial(nvec, p_hat)          # one call per replicate, records in ascending order
    return out.reshape(b_hi - b_lo, N, K, J, D)


def chunk_ranges(B: int, chunk: int, b_start: int = 1) -> list[tuple[int, int]]:
    """Replicates are numbered b = 1..B (prereg §6.2)."""
    return [(lo, min(lo + chunk, b_start + B)) for lo in range(b_start, b_start + B, chunk)]


def run(counts: np.ndarray, shots: np.ndarray, W: np.ndarray, phase: int, cell_index: int, B: int, chunk: int,
        replicate_fn: ReplicateFn, ckpt_dir: Path, stop_after_chunks: int | None = None, log=None) -> list[Path]:
    """Compute (or resume) all chunks; returns the ordered checkpoint paths."""
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    done = 0
    for lo, hi in chunk_ranges(B, chunk):
        p = ckpt_dir / f"chunk_{lo:06d}_{hi:06d}.npz"
        paths.append(p)
        if p.exists():
            continue
        if stop_after_chunks is not None and done >= stop_after_chunks:
            raise InterruptedError(f"stopped before chunk {lo}-{hi}")
        C = resample_chunk(counts, shots, phase, cell_index, lo, hi)
        V = (C / shots[None, ..., None]) @ W
        stats = replicate_fn(V)
        tmp = p.with_suffix(".tmp.npz")
        np.savez(tmp, b_lo=lo, b_hi=hi, **stats)
        tmp.rename(p)                                   # atomic: a partial chunk never counts as finished
        done += 1
        if log:
            log(lo, hi)
    return paths


def assemble(paths: list[Path]) -> dict[str, np.ndarray]:
    parts = [np.load(p) for p in paths]
    keys = [k for k in parts[0].files if k not in ("b_lo", "b_hi")]
    expected = 1
    for z in parts:
        assert int(z["b_lo"]) == expected, "checkpoint gap"
        expected = int(z["b_hi"])
    return {k: np.concatenate([z[k] for z in parts]) for k in keys}


def linear_quantile(sorted_vals: np.ndarray, q: float) -> float:
    """EQ-B12 on the extended real line (no arithmetic on infinities)."""
    b = len(sorted_vals)
    h = q * (b - 1)
    lo = int(np.floor(h))
    x1 = sorted_vals[lo]
    x2 = sorted_vals[min(lo + 1, b - 1)]
    if np.isinf(x1):
        return float(x1)
    if np.isinf(x2):
        return float(x2) if h - lo > 0 else float(x1)
    return float(x1 + (h - lo) * (x2 - x1))


def percentile_interval(values: np.ndarray, q_lo: float, q_hi: float):
    """values with nan = undefined; conservative placement (prereg §6.3)."""
    v = np.asarray(values, float)
    defined = v[~np.isnan(v)]
    u = int(v.size - defined.size)
    lo_vals = np.sort(np.concatenate([defined, np.full(u, -np.inf)]))
    hi_vals = np.sort(np.concatenate([defined, np.full(u, np.inf)]))
    lo, hi = linear_quantile(lo_vals, q_lo), linear_quantile(hi_vals, q_hi)
    flags = []
    if np.isinf(lo) or np.isinf(hi):
        flags.append("UNDEFINED")
    if defined.size and np.unique(defined).size == 1:
        flags.append("DEGENERATE_CONSTANT")
    if not flags and 0.5 * (hi - lo) < 1e-12:
        flags.append("DEGENERATE_COLLAPSED")
    return lo, hi, u, flags


Q_PRIMARY = (1.0 / 9600.0, 1.0 - 1.0 / 9600.0)   # alpha_e / 2 with alpha_e = 0.05 / 240, exact
Q_REPORTED = (0.025, 0.975)
